### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by kngwyu**
This PR:
- updates setup.py not to use duplicated `imp`,
  - I resembled other deepmind's repo for searching `__version__`, but used `re`. I can fix this if you prefer to line searching like other repos.
- makes `absl-py` test dependency since it is only used for testing, and
- updates `requirements.txt`. `absl-py==0.7.1` is actually incompatible with this package.

### CODE REVIEW

**Comment by kngwyu** [comment]
@googlebot I signed it!

**Comment by alimuldal** [comment]
> updates setup.py not to use duplicated imp,
> I resembled other deepmind's repo for searching __version__, but used re. I can fix this if you prefer to line searching like other repos.

By "duplicated"  you mean "deprecated"? I'm not against replacing it, but I'd much rather stick to using the import machinery rather than using regexes which tend to be more brittle and harder to understand. It looks like we could use `importlib.machinery.SourceFileLoader` instead.

> makes absl-py test dependency since it is only used for testing

We do use `absl.logging` in `dm_env.test_utils` which isn't a test, but rather a utility module for defining tests.

> `absl-py==0.7.1` is actually incompatible with this package.

I don't think this is true - our integration tests are currently passing against all the fixed versions in `requirements.txt`.

**Comment by kngwyu** [comment]
Thanks for your feedback. Now, this PR only replaces `imp`.

**Comment by alimuldal** [comment]
Actually it seems that `SourceFileLoader.load_module` is [also deprecated](https://docs.python.org/3/library/importlib.html#importlib.machinery.SourceFileLoader.load_module). I can write around that though.

**Pull request merged**
